-- =============================================================
-- knowledge-mcp v0.1.0 clause catalog seed
-- Generated by scripts/generate-seed-sql.mjs. Do not hand-edit;
-- regenerate instead.
--
-- Sources (in-repo only):
--   backend/prisma/seeds/far/clauses.json (52 FAR clauses)
--   backend/prisma/seeds/far/dfars.json (15 DFARS clauses)
--   backend/src/services/complianceGapAnalysis.ts CLAUSE_LIBRARY
--     (2 FAR clauses not in the JSON catalog: 52.225-5, 52.232-33;
--      plainLanguage mapped to summary)
--
-- The text column carries an explicit summary-level marker because
-- full clause text has not been ingested and must not be generated
-- from model memory. Idempotent: ON CONFLICT DO NOTHING.
--
-- Apply (PowerShell):
--   Get-Content scripts/seed-clause-catalog.sql -Raw |
--     docker exec -i bytescon_postgres psql -U bytescon_user -d bytescon_platform
-- =============================================================

BEGIN;

-- ---------- far_clauses (54 rows) ----------
INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-203-3', '52.203-3', '52', '52.2', 'Gratuities', '3.202', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'BPA']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Government may terminate the contract if the contractor or its agents offered a gratuity to influence award. Bidders with active gratuity findings cannot proceed.', ARRAY['ETHICS', 'REPRESENTATIONS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-203-5', '52.203-5', '52', '52.2', 'Covenant Against Contingent Fees', '3.404', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Bidder warrants no contingent fee was paid to secure the contract (except bona-fide employees / agencies).', ARRAY['ETHICS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-203-13', '52.203-13', '52', '52.2', 'Contractor Code of Business Ethics and Conduct', '3.1004', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, 6500000, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractors with awards >$6M and POP >120 days must maintain a written code of ethics, internal control system, and ethics training program.', ARRAY['ETHICS', 'COMPLIANCE_PROGRAM']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-1', '52.204-1', '52', '52.2', 'Approval of Contract', '4.103', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contract not binding until signed by approving authority.', ARRAY['AUTHORITY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-7', '52.204-7', '52', '52.2', 'System for Award Management', '4.1105(a)(1)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'BPA', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror must be registered in SAM at proposal submission and through award. Active SAM registration is a hard prerequisite.', ARRAY['SAM', 'REGISTRATION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-8', '52.204-8', '52', '52.2', 'Annual Representations and Certifications', '4.1202', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror''s reps and certs in SAM are incorporated by reference. Reps must be current.', ARRAY['REPRESENTATIONS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-10', '52.204-10', '52', '52.2', 'Reporting Executive Compensation and First-Tier Subcontract Awards', '4.1403', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, 30000, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must report first-tier subcontract awards >$30K and executive compensation in FFATA / FSRS.', ARRAY['TRANSPARENCY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-13', '52.204-13', '52', '52.2', 'System for Award Management Maintenance', '4.1105(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'BPA']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must maintain accurate SAM registration through life of contract.', ARRAY['SAM']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-16', '52.204-16', '52', '52.2', 'Commercial and Government Entity Code Reporting', '4.1804', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror must report CAGE code and any prior CAGE codes for affiliates.', ARRAY['CAGE']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-24', '52.204-24', '52', '52.2', 'Representation Regarding Certain Telecommunications and Video Surveillance Services or Equipment', '4.2105(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Section 889 prohibits use of covered Chinese telecom/surveillance equipment (Huawei, ZTE, Hikvision, Dahua, Hytera). Offeror must represent compliance.', ARRAY['SECTION_889', 'SUPPLY_CHAIN']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-204-25', '52.204-25', '52', '52.2', 'Prohibition on Contracting for Certain Telecommunications and Video Surveillance Services or Equipment', '4.2105(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Government may not procure or extend a contract with any entity that uses covered telecom equipment as substantial component or critical technology.', ARRAY['SECTION_889', 'SUPPLY_CHAIN']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-209-1', '52.209-1', '52', '52.2', 'Qualification Requirements', '9.206-2', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'When qualification requirements apply, offeror must demonstrate qualified product/service. Past performance must be relevant and recent.', ARRAY['PAST_PERFORMANCE', 'QUALIFICATION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-209-5', '52.209-5', '52', '52.2', 'Certification Regarding Responsibility Matters', '9.104-7(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror must certify it has not within the last 3 years been convicted of fraud, antitrust violations, tax evasion, or had a contract terminated for default.', ARRAY['RESPONSIBILITY', 'CERTIFICATION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-209-7', '52.209-7', '52', '52.2', 'Information Regarding Responsibility Matters', '9.104-7(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offerors with active federal contracts/grants totaling >$10M must disclose FAPIIS information including criminal proceedings, civil judgments, and terminations.', ARRAY['RESPONSIBILITY', 'FAPIIS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-212-1', '52.212-1', '52', '52.2', 'Instructions to Offerors—Commercial Products and Commercial Services', '12.301(b)(1)', ARRAY['COMMERCIAL', 'FFP']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Standard instructions for commercial-item proposals: format, content, multiple awards, evaluation period.', ARRAY['INSTRUCTIONS', 'SECTION_L']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-212-2', '52.212-2', '52', '52.2', 'Evaluation—Commercial Products and Commercial Services', '12.301(c)', ARRAY['COMMERCIAL', 'FFP']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Evaluation factors for commercial-item awards. Government identifies factors and relative importance.', ARRAY['EVALUATION', 'SECTION_M']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-212-3', '52.212-3', '52', '52.2', 'Offeror Representations and Certifications—Commercial Products and Commercial Services', '12.301(b)(2)', ARRAY['COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Comprehensive reps and certs covering size status, set-aside eligibility, ownership, debarment, foreign ownership, telecom restrictions.', ARRAY['REPRESENTATIONS', 'CERTIFICATIONS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-212-4', '52.212-4', '52', '52.2', 'Contract Terms and Conditions—Commercial Products and Commercial Services', '12.301(b)(3)', ARRAY['COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Standard terms and conditions for commercial-item contracts. Replaces many uniform clauses.', ARRAY['TERMS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-212-5', '52.212-5', '52', '52.2', 'Contract Terms and Conditions Required to Implement Statutes or Executive Orders—Commercial Products and Commercial Services', '12.301(b)(4)', ARRAY['COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Master commercial flow-down clause. Lists statutorily required clauses that must flow down to commercial subcontracts (the commercial complement to 52.244-6).', ARRAY['FLOW_DOWN', 'STATUTORY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-215-1', '52.215-1', '52', '52.2', 'Instructions to Offerors—Competitive Acquisition', '15.209(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Standard Section L instructions for negotiated competitive acquisitions: late offers, withdrawal, oral presentations, contract awards.', ARRAY['INSTRUCTIONS', 'SECTION_L']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-215-2', '52.215-2', '52', '52.2', 'Audit and Records—Negotiation', '15.209(b)', ARRAY['T_AND_M', 'COST_REIMB', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must maintain records and permit government audit; flows down to cost-reimbursement and T&M subcontracts.', ARRAY['AUDIT', 'DCAA']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-3', '52.219-3', '52', '52.2', 'Notice of HUBZone Set-Aside or Sole Source Award', '19.1309(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['HUBZONE']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Set-aside restricted to certified HUBZone small businesses. Offeror must be SBA-certified HUBZone at offer and award.', ARRAY['SET_ASIDE', 'HUBZONE']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-4', '52.219-4', '52', '52.2', 'Notice of Price Evaluation Preference for HUBZone Small Business Concerns', '19.1309(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['HUBZONE']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', '10% price evaluation preference for HUBZone small businesses in unrestricted full-and-open competitions.', ARRAY['HUBZONE', 'EVALUATION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-6', '52.219-6', '52', '52.2', 'Notice of Total Small Business Set-Aside', '19.508(c)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['SMALL_BUSINESS']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Acquisition restricted to small business concerns. Offeror must qualify as small under the assigned NAICS code''s size standard.', ARRAY['SET_ASIDE', 'SMALL_BUSINESS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-8', '52.219-8', '52', '52.2', 'Utilization of Small Business Concerns', '19.708(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must use small businesses, including HUBZone, SDVOSB, WOSB, and 8(a) firms, to the maximum practicable extent.', ARRAY['SMALL_BUSINESS', 'SUBCONTRACTING']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-9', '52.219-9', '52', '52.2', 'Small Business Subcontracting Plan', '19.708(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, 750000, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Other-than-small contractors with awards >$750K (>$1.5M for construction) must submit and execute a small business subcontracting plan with measurable goals.', ARRAY['SUBCONTRACTING_PLAN', 'SMALL_BUSINESS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-14', '52.219-14', '52', '52.2', 'Limitations on Subcontracting', '19.507(e)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['SMALL_BUSINESS', 'SDVOSB', 'WOSB', 'EDWOSB', 'HUBZONE', 'EIGHT_A']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'On set-aside contracts: services — prime cannot subcontract more than 50%; supplies — 50% of cost of manufacturing; construction — 85% (general) or 75% (specialty trade).', ARRAY['LIMITATIONS_ON_SUBCONTRACTING', 'SET_ASIDE']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-17', '52.219-17', '52', '52.2', 'Section 8(a) Award', '19.811-3(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['EIGHT_A']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Award restricted to 8(a) program participants. SBA holds the contract and subcontracts performance to the 8(a) firm.', ARRAY['SET_ASIDE', 'EIGHT_A']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-27', '52.219-27', '52', '52.2', 'Notice of Service-Disabled Veteran-Owned Small Business Set-Aside', '19.1407', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['SDVOSB']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Set-aside for service-disabled veteran-owned small businesses. Offeror must be SBA-certified SDVOSB at offer and award.', ARRAY['SET_ASIDE', 'SDVOSB']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-28', '52.219-28', '52', '52.2', 'Post-Award Small Business Program Rerepresentation', '19.309(c)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must rerepresent its size status before exercise of an option, after a merger/acquisition, or every five years.', ARRAY['SIZE_REREP']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-29', '52.219-29', '52', '52.2', 'Notice of Set-Aside for Economically Disadvantaged Women-Owned Small Business', '19.1507', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['EDWOSB']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Set-aside for SBA-certified Economically Disadvantaged Women-Owned Small Businesses.', ARRAY['SET_ASIDE', 'EDWOSB']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-30', '52.219-30', '52', '52.2', 'Notice of Set-Aside for Women-Owned Small Business', '19.1507', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY['WOSB']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Set-aside for SBA-certified Women-Owned Small Businesses in eligible NAICS codes.', ARRAY['SET_ASIDE', 'WOSB']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-219-33', '52.219-33', '52', '52.2', 'Nonmanufacturer Rule', '19.505', ARRAY['FFP', 'IDIQ']::text[], ARRAY['SMALL_BUSINESS', 'SDVOSB', 'WOSB', 'EDWOSB', 'HUBZONE', 'EIGHT_A']::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'On set-aside supply contracts a small business reseller must supply the product of a small business manufacturer (or have a waiver).', ARRAY['NONMANUFACTURER', 'SET_ASIDE']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-222-3', '52.222-3', '52', '52.2', 'Convict Labor', '22.202', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor cannot use federal-prison-made products unless authorized.', ARRAY['LABOR']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-222-6', '52.222-6', '52', '52.2', 'Construction Wage Rate Requirements', '22.407(a)', ARRAY['FFP']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Davis-Bacon Act: construction contractors must pay locally prevailing wages. Wage determination from sam.gov is incorporated.', ARRAY['DAVIS_BACON', 'WAGE_DETERMINATION', 'CONSTRUCTION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-222-21', '52.222-21', '52', '52.2', 'Prohibition of Segregated Facilities', '22.810(a)(1)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor cannot maintain or provide segregated facilities.', ARRAY['EEO', 'LABOR']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-222-26', '52.222-26', '52', '52.2', 'Equal Opportunity', '22.810(e)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, 10000, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Executive Order 11246 EEO clause. Required for awards >$10K. Flows down to subcontracts >$10K.', ARRAY['EEO', 'LABOR']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-222-41', '52.222-41', '52', '52.2', 'Service Contract Labor Standards', '22.1006(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Service Contract Act: services contractors must pay locally prevailing wages and fringe benefits per the wage determination.', ARRAY['SCA', 'WAGE_DETERMINATION', 'LABOR']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-222-50', '52.222-50', '52', '52.2', 'Combating Trafficking in Persons', '22.1705(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor and subs must not engage in trafficking activities. Compliance plan required for awards >$500K outside the U.S.', ARRAY['LABOR', 'TRAFFICKING']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-225-1', '52.225-1', '52', '52.2', 'Buy American—Supplies', '25.1101(a)(1)', ARRAY['FFP', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Only domestic end products may be supplied unless an exception applies. Iron, steel, and manufactured-end-product cost-of-components thresholds apply.', ARRAY['BUY_AMERICAN', 'SUPPLY_CHAIN']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-225-3', '52.225-3', '52', '52.2', 'Buy American—Free Trade Agreements—Israeli Trade Act', '25.1101(b)(1)', ARRAY['FFP', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Domestic or designated-country end products only. Lists countries qualifying under FTAs and the Israeli Trade Act.', ARRAY['BUY_AMERICAN', 'TRADE_AGREEMENTS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-225-13', '52.225-13', '52', '52.2', 'Restrictions on Certain Foreign Purchases', '25.1103(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Cannot acquire items from sources subject to sanctions (OFAC list).', ARRAY['SANCTIONS', 'SUPPLY_CHAIN']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-227-14', '52.227-14', '52', '52.2', 'Rights in Data—General', '27.409(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Government acquires unlimited rights in data first produced under the contract. Limited and restricted rights available under specific conditions.', ARRAY['DATA_RIGHTS', 'IP']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-230-2', '52.230-2', '52', '52.2', 'Cost Accounting Standards', '30.201-4(a)', ARRAY['COST_REIMB', 'IDIQ', 'T_AND_M']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must comply with all 19 Cost Accounting Standards if award is CAS-covered (>$2M and not exempt). Disclosure statement required for full coverage.', ARRAY['CAS', 'COST_PRINCIPLES']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-230-3', '52.230-3', '52', '52.2', 'Disclosure and Consistency of Cost Accounting Practices', '30.201-4(b)', ARRAY['COST_REIMB', 'IDIQ', 'T_AND_M']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Modified CAS coverage: contractor must comply with CAS 401, 402, 405, 406 only.', ARRAY['CAS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-232-25', '52.232-25', '52', '52.2', 'Prompt Payment', '32.908(c)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Government will pay invoices within 30 days; interest accrues on late payments.', ARRAY['PAYMENT']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-232-39', '52.232-39', '52', '52.2', 'Unenforceability of Unauthorized Obligations', '32.706-3', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Click-through and EULA terms in commercial software unenforceable to extent they conflict with federal law.', ARRAY['TERMS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-233-3', '52.233-3', '52', '52.2', 'Protest After Award', '33.106(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'On post-award protest, government may direct contractor to stop work; contractor entitled to costs incurred.', ARRAY['DISPUTES']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-244-6', '52.244-6', '52', '52.2', 'Subcontracts for Commercial Products and Commercial Services', '44.403', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY[]::text[], ARRAY[]::text[], true, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'When subcontracting for commercial items, only the listed clauses (52.203-13, 52.203-19, 52.204-23, 52.204-25, 52.219-8, 52.222-21, 52.222-26, 52.222-50, 52.225-26, 52.226-6, 52.247-64) flow down — limiting commercial-sub flow-down burden.', ARRAY['FLOW_DOWN', 'SUBCONTRACTING', 'COMMERCIAL']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-246-15', '52.246-15', '52', '52.2', 'Certificate of Conformance', '46.315', ARRAY['FFP', 'IDIQ']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'When authorized in lieu of source inspection, contractor furnishes a certificate that supplies/services conform to contract requirements.', ARRAY['QUALITY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-252-1', '52.252-1', '52', '52.2', 'Solicitation Provisions Incorporated by Reference', '52.107(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Listed solicitation provisions are incorporated by reference with the same force as if printed in full.', ARRAY['INCORPORATION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-252-2', '52.252-2', '52', '52.2', 'Clauses Incorporated by Reference', '52.107(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Listed contract clauses are incorporated by reference with the same force as if printed in full. Full text available at acquisition.gov.', ARRAY['INCORPORATION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-225-5', '52.225-5', '52', '52.2', 'Trade Agreements Act', NULL, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Products you supply must be made in the U.S. or a country with a U.S. trade agreement (specific list). Excludes most non-WTO countries.', ARRAY['TRADE_AGREEMENTS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO far_clauses
  (id, code, "partNumber", "subpartNumber", title, "prescribedAt", "applicableContractTypes", "setAsideTriggers", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "prohibitedClauseCodes", "commercialItemException", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-far-52-232-33', '52.232-33', '52', '52.2', 'Payment by Electronic Funds Transfer - System for Award Management', NULL, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], false, NULL, ARRAY[]::text[], ARRAY[]::text[], false, false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'You must accept payment via Electronic Funds Transfer (EFT). Banking info goes in your SAM.gov profile.', ARRAY['PAYMENT']::text[])
ON CONFLICT DO NOTHING;

-- ---------- dfars_clauses (15 rows) ----------
INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-203-7000', '252.203-7000', '252', 'Requirements Relating to Compensation of Former DoD Officials', '203.171-4', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must certify it has informed all covered DoD officials of post-employment restrictions.', ARRAY['ETHICS', 'POST_GOVERNMENT_EMPLOYMENT']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-204-7008', '252.204-7008', '252', 'Compliance with Safeguarding Covered Defense Information Controls', '204.7304(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror represents it will implement NIST SP 800-171 security requirements when handling Covered Defense Information.', ARRAY['CYBERSECURITY', 'CDI']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-204-7012', '252.204-7012', '252', 'Safeguarding Covered Defense Information and Cyber Incident Reporting', '204.7304(c)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY['DOD']::text[], true, NULL, ARRAY['252.204-7008']::text[], true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must implement NIST SP 800-171 controls for Covered Defense Information and report cyber incidents to DoD within 72 hours. Flows down to ALL subcontractors.', ARRAY['CYBERSECURITY', 'CDI', 'NIST_800_171', 'INCIDENT_REPORTING']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-204-7019', '252.204-7019', '252', 'Notice of NIST SP 800-171 DoD Assessment Requirements', '204.7304(d)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror must have a current NIST SP 800-171 self-assessment posted to SPRS (Supplier Performance Risk System) before award.', ARRAY['NIST_800_171', 'SPRS', 'CYBERSECURITY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-204-7020', '252.204-7020', '252', 'NIST SP 800-171 DoD Assessment Requirements', '204.7304(e)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], true, NULL, ARRAY[]::text[], true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must provide DoD access for higher-tier assessments and ensure subs at all tiers have current SPRS scores.', ARRAY['NIST_800_171', 'SPRS', 'CYBERSECURITY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-204-7021', '252.204-7021', '252', 'Cybersecurity Maturity Model Certification Requirements', '204.7503(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB', 'COMMERCIAL']::text[], ARRAY['DOD']::text[], true, NULL, ARRAY[]::text[], true, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must achieve and maintain the CMMC level specified in the solicitation. Flows down to subs handling FCI/CUI.', ARRAY['CMMC', 'CYBERSECURITY']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-204-7024', '252.204-7024', '252', 'Notice on the Use of the Supplier Performance Risk System', '204.7604', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offerors notified that SPRS supplier risk and item risk data will be considered in source selection.', ARRAY['SPRS', 'PAST_PERFORMANCE']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-215-7008', '252.215-7008', '252', 'Only One Offer', '215.371-7', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'If only one offer is received, government may request cost or pricing data.', ARRAY['COMPETITION']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-219-7003', '252.219-7003', '252', 'Small Business Subcontracting Plan (DoD Contracts)', '219.708(b)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], true, 750000, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'DoD-specific small business subcontracting plan requirements (in addition to FAR 52.219-9).', ARRAY['SUBCONTRACTING_PLAN', 'SMALL_BUSINESS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-225-7000', '252.225-7000', '252', 'Buy American—Balance of Payments Program Certificate', '225.1101(a)', ARRAY['FFP', 'IDIQ']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Offeror certifies whether end products are domestic or qualifying-country end products under DoD Balance of Payments program.', ARRAY['BUY_AMERICAN', 'BALANCE_OF_PAYMENTS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-225-7001', '252.225-7001', '252', 'Buy American and Balance of Payments Program', '225.1101(b)', ARRAY['FFP', 'IDIQ']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'DoD contractors must deliver only domestic or qualifying-country end products unless an exception applies.', ARRAY['BUY_AMERICAN', 'BALANCE_OF_PAYMENTS']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-225-7048', '252.225-7048', '252', 'Export-Controlled Items', '225.7901-4', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], true, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Contractor must comply with ITAR and EAR for export-controlled items. Flows down to all subs handling such items.', ARRAY['EXPORT_CONTROL', 'ITAR', 'EAR']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-227-7013', '252.227-7013', '252', 'Rights in Technical Data—Noncommercial Items', '227.7103-6(a)', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], false, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Government rights in technical data for noncommercial items. Defines unlimited, limited, government-purpose, and SBIR rights.', ARRAY['DATA_RIGHTS', 'IP']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-244-7000', '252.244-7000', '252', 'Subcontracts for Commercial Products and Commercial Services', '244.403', ARRAY['FFP', 'T_AND_M', 'IDIQ', 'COST_REIMB']::text[], ARRAY['DOD']::text[], true, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'DoD-specific limits on flow-down to commercial subcontracts. Defines which DFARS clauses must, may, and must not flow down to commercial subs.', ARRAY['FLOW_DOWN', 'SUBCONTRACTING', 'COMMERCIAL', 'DOD']::text[])
ON CONFLICT DO NOTHING;

INSERT INTO dfars_clauses
  (id, code, "partNumber", title, "prescribedAt", "applicableContractTypes", "agencyTriggers", "flowDownRequired", "flowDownThreshold", "prerequisiteClauseCodes", "isBlocking", "effectiveDate", "lastRevisedDate", text, summary, tags)
VALUES ('knowledge-mcp-seed-dfars-252-246-7007', '252.246-7007', '252', 'Contractor Counterfeit Electronic Part Detection and Avoidance System', '246.870-3', ARRAY['FFP', 'IDIQ']::text[], ARRAY['DOD']::text[], true, NULL, ARRAY[]::text[], false, NULL, NULL, '[Summary-level entry, full clause text not yet ingested]', 'Covered contractors must establish a counterfeit electronic part detection/avoidance system per the listed criteria.', ARRAY['COUNTERFEIT', 'SUPPLY_CHAIN']::text[])
ON CONFLICT DO NOTHING;

COMMIT;
